### ISSUE TITLE
IllegalArgumentException: No config chosen

### ISSUE THREAD

**Issue by chRyNaN** [sinch/android-video-calling#1]
When testing the video calling features with an emulator, the app crashes with an `IllegalArgumentException: No config chosen` error. The error comes from a `GLSurfaceView`, most likely used to display the video, and can be contributed to the `EGLConfigChooser`. The problem can most likely be fixed with a call to `setEGLConfigChooser(8 , 8, 8, 8, 16, 0);` in the custom GLSurfaceView class. More information can be found [here](http://stackoverflow.com/a/14167359/1478764) and [here](http://stackoverflow.com/a/16732614/1478764). Stacktrace: 

```java
com.myapp E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 190
    Process: com.myapp, PID: 3034
    java.lang.IllegalArgumentException: No config chosen
            at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:869)
            at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1023)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1400)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

**Comment by slavasav** [comment]
Please try enabling the "Use Host GPU" option, or enabling "GPU emulation" for the emulator, as described here http://developer.android.com/tools/devices/emulator.html. This has been tested with API 22.
In general emulator is not recommended to evaluate the video solution as it is slow and does not support camera.

**Comment by chRyNaN** [comment]
Unfortunately, I had the "Use Host GPU" option already enabled when testing. The problem only seems to persist on the emulator; on handsets it works fine. Though, the emulator does allow for webcam integration. I'm running a targetSDKVersion of 22 and a minSDKVersion of 16. It seems I may have to result to only testing on handsets.
