### ISSUE TITLE
java.lang.RuntimeException: Fail to connect to camera service

### ISSUE THREAD

**Issue by miceliedna** [sinch/android-video-calling#3]
Working with android 5.1.1 and getting this error with video calling.

E/org.webrtc.Logging: CameraEnumerator: java.lang.RuntimeException: Fail to connect to camera service
                                                                       at android.hardware.Camera.<init>(Camera.java:545)
                                                                       at android.hardware.Camera.open(Camera.java:385)
                                                                       at org.webrtc.sinch.CameraEnumerator.enumerateFormats(CameraEnumerator.java:67)
                                                                       at org.webrtc.sinch.CameraEnumerator.getSupportedFormats(CameraEnumerator.java:53)
                                                                       at org.webrtc.sinch.CameraEnumerationAndroid.getSupportedFormats(CameraEnumerationAndroid.java:63)
                                                                       at org.webrtc.sinch.CameraEnumerationAndroid.getSupportedFormatsAsJson(CameraEnumerationAndroid.java:172)
                                                                       at org.webrtc.sinch.VideoCapturerAndroid.getSupportedFormatsAsJson(VideoCapturerAndroid.java:369)

**Comment by williandrade** [comment]
Is necessary you put the permission at the AndroidManifest.xml, the permission for solve your problem is     <uses-permission android:name="android.permission.CAMERA" />

Hope that helps.
